spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      eclipselink:
        ddl-generation: create-tables
        logging.level: FINE
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=demo
    username: postgres
    password: postgres