spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      eclipselink:
        ddl-generation: drop-and-create-tables
        logging.level: FINE
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres